config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :projects, only: [:index]
    resources :project_images, only: [:index, :show]
    resources :contacts, only: [:create]
  end

  namespace :admin do
    root to: 'projects#index'

    resources :projects, only: [:index, :show, :new, :create, :edit, :update]
  end

  devise_for :users

  mount_ember_app :frontend, to: '/'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true

end

app/models/project.rb
class Project < ApplicationRecord

  has_many :project_images, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings

  validates :title, presence: true
  validates :description, presence: true

  accepts_nested_attributes_for :project_images
  accepts_nested_attributes_for :tags

end

app/models/project_image.rb
class ProjectImage < ApplicationRecord

  belongs_to :project

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings
  has_many :projects, through: :taggings

  validates :name, presence: true

end

app/models/tagging.rb
class Tagging < ApplicationRecord

  belongs_to :tag
  belongs_to :project

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :authenticate_user!

  layout 'admin'

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController

  def index
    @projects = Project.all
  end

  def show
    @project = project
  end

  def new
    @project = Project.new
    @project_image = @project.project_images.build
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to new_admin_project_path, flash: { success: 'Project successfully saved.' }
    else
      render :new
    end
  end

  def edit
    @project = project
  end

  def update
    @project = project
    if @project.update(project_params)
      redirect_to new_admin_project_path, flash: { success: 'Project successfully saved.' }
    else
      render :edit
    end
  end

  private

  def project
    Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:id, :title, :description, project_images_attributes: [:id, :filepicker_url, :_destroy], tags_attributes: [:id, :name, :_destroy])
  end

end

app/controllers/api/contacts_controller.rb
class Api::ContactsController < ApplicationController

  def create
    @contact = Contact.new(contact_params)
    @contact.save
    ContactMailer.contact_mail(@contact).deliver_now
    render json: @contact
  end

  private

  def contact_params
    res = ActiveModelSerializers::Deserialization.jsonapi_parse(params)
  end

end

app/controllers/api/project_images_controller.rb
class Api::ProjectImagesController < ApplicationController

  def index
    @project_images = ProjectImage.all
    render json: @project_images
  end

  def show
    @project_image = ProjectImage.find(params[:id])
    render json: @project_image
  end

end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController

  def index
    @projects = Project.all.order(created_at: :desc)
    render json: @projects, include: ['project_images', 'tags']
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # protect_from_forgery with: :exception

  helper FilepickerRails::Engine.helpers

  def after_sign_in_path_for(resource)
    admin_root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/projects/_tag_fields.html.erb
<%= f.input :name %>
<%= link_to_remove_association "remove tag", f %>

app/views/admin/projects/edit.html.erb
<%= simple_form_for @project, url: admin_project_path, method: :patch do |form| %>

  <%= form.error_notification %>

  <%= form.input :title %>
  <%= form.input :description %>

  <%= form.simple_fields_for :project_images do |f| %>

    <%= f.filepicker_field :filepicker_url %>

  <% end %>

  <%= form.simple_fields_for :tags do |tag| %>

    <%= render 'tag_fields', f: tag %>

  <% end %>

  <div class='links'>

    <%= link_to_add_association 'add tag', form, :tags, class: 'btn btn-primary' %>

    <%= form.submit %>

  </div>

<% end %>

app/views/admin/projects/index.html.erb
<div class='container'>

  <div class='row'>
    <div class='col-xs-12'>
      <%= link_to 'New project', new_admin_project_path, class: 'btn btn-primary'%>
    </div>
  </div>

  <div class='row'>

    <div class='col-xs-12'>

      <% @projects.each do |project| %>

        <div class='panel panel-default'>
          <div class='panel-heading'>
            <%= project.title %>
          </div>
          <div class='panel-body'>
            <p>
              <%= project.description %>
            </p>
            <% project.tags&.each do |tag| %>
              <div class='label label-default'>
                <%= tag.name %>
              </div>
            <% end %>
          </div>
          <div class='panel-footer'>
            <%= link_to 'Edit', edit_admin_project_path(project) %>
          </div>
        </div>

      <% end %>

    </div>

  </div>

</div>

app/views/admin/projects/new.html.erb
<%= simple_form_for @project, url: admin_projects_path do |form| %>

  <%= form.error_notification %>

  <%= form.input :title %>
  <%= form.input :description %>

  <%= form.simple_fields_for :project_images do |f| %>

    <%= f.filepicker_field :filepicker_url %>

  <% end %>

  <%= form.submit %>

<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleEmberApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: 'defer' %>
    <%= filepicker_js_include_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleEmberApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>